2019-12-16 23:03:25,330 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:07:31,087 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:08:37,239 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:09:53,058 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:10:07,956 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:13:05,015 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:13:26,982 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:13:48,243 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:16:16,563 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:16:41,752 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-16 23:16:55,735 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:39:50,999 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:40:27,707 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:44:47,046 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:46:14,846 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:50:04,096 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 00:55:52,011 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:38:53,548 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:41:11,453 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:42:41,020 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:44:22,309 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:44:29,076 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 242, in index
    fig=make_figure(df,plot_arguments)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 39, in make_figure
    x=df[pa["xvals"]].tolist()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None
2019-12-17 01:50:56,477 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:51:25,798 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:51:54,411 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:52:47,680 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:53:18,643 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:54:27,892 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:58:01,065 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:58:14,396 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:58:22,657 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 01:58:59,803 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 02:01:15,779 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 02:03:31,672 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 02:03:36,960 ERROR: Exception on /index [POST] [in /Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 242, in index
    fig=make_figure(df,plot_arguments)
  File "/Users/jboucas/flask_dashboard/app/routes.py", line 39, in make_figure
    x=df[pa["xvals"]].tolist()
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/jboucas/flask_dashboard/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: None
2019-12-17 02:05:44,846 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
2019-12-17 02:06:40,154 INFO: Scatterplot startup [in /Users/jboucas/flask_dashboard/app/__init__.py:45]
